### ISSUE TITLE
golang based leveldb

### ISSUE THREAD

**Issue by ghost** [adamlofts/leveldb_dart#11]
https://github.com/syndtr/goleveldb

works on mobiles and all servers and desktops.

might be a good option for easy portability.

**Comment by adamlofts** [comment]
The c++ library has Mac / Android support. We just need someone who is using these platforms to contribute to the build process and build the dart extension that is in this repo. 

Still its an interesting idea but I think writing an extension for goleveldb would amount to a new dart library. Thanks for the suggestion.

**Comment by ghost** [comment]
You should think about it I feel.
The golang version has no c dependencies. You compile and it runs anywhere. It lowers a ton of integration heachaches.

But I can respect you want to stick with what you know.
