### ISSUE TITLE
Do you support flutter and Dart2?

### ISSUE THREAD

**Issue by allowthere** [adamlofts/leveldb_dart#13]
I'm trying to use leveldb in my flutter app (running in --preview-dart-2, when I tried removing it, I got an "Unknown scheme (dart-ext)" compiler error).

But when I do, I get a 
   
     E/flutter (11642): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unknown library tag.error: library handler failed
     E/flutter (11642): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.

runtime error.

It happens even if all I do is import the package (`import 'package:leveldb/leveldb.dart'`). 

My pubspec.yaml is
  
    dependencies:
      leveldb:
      flutter:
        sdk: flutter

I'm running this in and Android Emulator (Oreo on amd64)

**Comment by allowthere** [comment]
Sorry. Looks like you don't support android.

**Comment by adamlofts** [comment]
Yes there is no flutter support. (contributions welcome!)
