### ISSUE TITLE
Undefined symbol on your prebuilt shared object

### ISSUE THREAD

**Issue by dyu** [adamlofts/leveldb_dart#5]
After running ```pub get && pub run example/main.dart```, I get:
```
symbol lookup error: ///absolute/path/to/leveldb_dart/lib/libleveldb.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm
```

I'm on ubuntu 14.04 x64

**Comment by adamlofts** [comment]
Could you pull from master and try again.
I have improved the compatibility of the build and I think it should work on Ubuntu 14.04 now.

**Comment by dyu** [comment]
It works.
Sorry it took long to verify (didn't see the mail notification from gh)
