### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by adamlofts** [adamlofts/leveldb_dart#9]
It should be possible to build the dart extension on a mac. Please comment below if you are interested in supporting this feature.

Rough instructions would be:

1. Download leveldb sources and build the library statically
1. Update the makefile to build the extension
1. Run the test cases

**Comment by xylobol** [comment]
Hello! I'm interested in helping build out support. Have the steps changed at all?

**Comment by adamlofts** [comment]
The steps should be the same. The goal is to build a dynamic library like this file https://github.com/adamlofts/leveldb_dart/blob/master/lib/libleveldb.s but for mac and check it into the source tree.

The leveldb sources are linked statically into this library so the end user does not have to have leveldb installed. I've documented how to do this on linux in the makefile here https://github.com/adamlofts/leveldb_dart/blob/master/Makefile#L5

**Comment by adamlofts** [comment]
Fixed by @simonkuang thanks!
